Code Cleanup
gbowne1/reactsocialnetwork pull request #194
Opened 2023-04-28 07:19 UTC by promise-dash

I tried to resolve issue #183 
Updated the code based on the eslint and prettier configuration.

2023-04-28 07:50 UTC, gbowne1 requested changes
This was a lot of files to review but somewhat necessary to helo keep our code clean. 

There seems to be a merge conflct with this.

Seems to have worked though.

2023-04-28 14:36 UTC, promise-dash commented
Ok let me try resolving these conflicts

2023-04-29 06:48 UTC, promise-dash commented
The conflicting files are now been modified.

2023-04-29 06:53 UTC, gbowne1 commented
Looks like that fixed it.

2023-04-29 06:54 UTC, gbowne1 approved these changes
Approving fixes for merge.

2023-04-29 06:57 UTC, gbowne1 commented
Feel free to work on any of the issues.  We have some 3-4 months old.

2023-04-29 08:29 UTC, pawel975 approved these changes
Approve clean up.

2023-04-29 08:29 UTC, pawel975 commented on index.js
@gbowne1 is this file even needed? CRA runs local server.

2023-04-29 08:29 UTC, pawel975 commented on src/components/Theme/Theme.jsx
@gbowne1 is this file useful? We mainly provide colors from src/variables.css.

2023-04-29 08:34 UTC, gbowne1 commented on index.js
No, @pawel975 here are several files not needed for development. This is one of them.

In production, we will have to decide the full stack build. NodeJS, ExpressJS server.. etc. In that case we will have to build a server file. I don't know how much that CRA automates this.

That reminds me have you decided what to workon next?

2023-04-29 08:36 UTC, gbowne1 commented on src/components/Theme/Theme.jsx
This might be useful, but we are aleady using variables to control theme.  Theme.js (a theme controller) was a way of doing it before we had React 17 and MUI 5.

2023-04-29 16:08 UTC, pawel975 commented on index.js
CRA has production mode that generates build files. I have hosted multiple projects on Vercel that uses those build files. Not sure if manual NodeJS setup is needed.

If it goes about contribution, I didn't decided yet.

2023-04-29 18:18 UTC, gbowne1 commented on index.js
I hadnt gotten that far before, so wasnt sure.

2023-04-30 07:07 UTC, manuel12 commented
Will review this today.

2023-05-01 08:01 UTC, manuel12 approved these changes
Approving changes

2023-05-01 08:01 UTC, merged

2023-05-01 08:32 UTC, promise-dash commented
Thanks for merging my PR.

2023-05-01 08:36 UTC, gbowne1 commented
Youre welcome @promise-dash 

Feel free to work on any other issues you woukd like.